### PR TITLE
Bump Dependencies

### PR DESCRIPTION
**Pull request by LeonNissen**
# Bump Dependencies

## :gear: Release Notes 
- Updates all dependencies
- Uses new SpeziLLM Version 0.9.0 with MLX support
- GPT 4o can be selected 

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Looks great; thank you @LeonNissen!

I think there is a build error due to a bump of XCTextExtensions (`dismissKeyboard` argument) that needs to be fixed before the merge.

**Review by vishnuravi — APPROVED** [review]
This looks great, thanks for the updates @LeonNissen!

**Comment by LeonNissen** [comment]
Update (as discuss with @vishnuravi): Will wait for https://github.com/StanfordSpezi/SpeziLLM/pull/81 to be merged since it fixes a bug running the local LLM on the simulator.

**Comment by vishnuravi** [comment]
The fix for running the local LLM in a simulator has been merged (thank you @LeonNissen), so we can merge this PR. The UI tests are flaky, they pass locally for both myself and @LeonNissen but fail intermittently on the runner.

**Comment by vishnuravi** [comment]
All checks passed except for patch coverage, which we cannot increase further at the moment, due to the changes in this PR being related to SpeziLLMLocal, which does not run on iOS simulators. Therefore, we will merge despite the patch coverage check not passing.

**Pull request merged**
